services:

  blue:
    image: cicd-task-api:blue
    container_name: cicd-task-api-blue
    ports:
      - "8001:8000"
    restart: unless-stopped

  green:
    image: cicd-task-api:green
    container_name: cicd-task-api-green
    ports:
      - "8002:8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: cicd-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped